worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name lightcrypto.website www.lightcrypto.website;
        root /var/www/crypto/build;
        index index.html;

        gzip on;
        gzip_comp_level 5;
        gzip_types application/javascript text/css image/svg+xml;

        location / {
            try_files $uri /index.html;
        }

        location /static/ {
            try_files $uri $uri/ =404;
        }
    }
}